config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]                                          
as :user do
  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
  put 'users' => 'devise/registrations#update', :as => 'user_registration'            
end
  

  root :to => "posts#index"

resources :posts

namespace :admin do
  resources :posts
  end

controller :posts do
  get :daycare
  get :hotel
  get :about
  get :grooming
  get :faqs
end

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :admin_required
  before_action :find_photos
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end


  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to admin_posts_path
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_posts_path
    else
      render :edit
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, alert: '文章已刪除'
  end
  private

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_photos
  def index
    @posts = Post.order("id DESC")
     set_page_title "寵物安親｜寵物住宿｜寵物美容"
     set_page_description (" 一家三口動物旅館成立於2015年10月，位於桃園市桃園區民生路上，一家三口是一間安全、健康、溫暖的動物旅館，在這裡提供寵物美容、寵物住宿、寵物安親的服務。地址：桃園市桃園區民生路495號之9 33043，電話是03-3363252，email：elite.eah@gmail.com")
     set_page_keywords ('一家三口,寵物安親,寵物美容,寵物住宿,寵物,狗狗,貓咪,狗貓夜間急診,24小時動物醫院')
  end

  def show
    @post = Post.find(params[:id])
     set_page_title "最新消息"
     set_page_description ("一家三口動物旅館:地址：桃園市桃園區民生路495號之9 33043，電話是03-3363252，email：elite.eah@gmail.com，一家三口動物旅館最新消息，我們有寵物美容、寵物住宿、寵物安親優質服務。")
     set_page_keywords ('一家三口,寵物安親,寵物美容,寵物住宿,狗狗,貓咪,寵物,狗貓夜間急診,24小時動物醫院')
  end

  def daycare
    set_page_title "寵物安親Daycare"
    set_page_description ("一家三口動物旅館:地址：桃園市桃園區民生路495號之9 33043，電話是03-3363252，email：elite.eah@gmail.com，一家三口動物旅館寵物安親服務，一家三口動物旅館秉持著貼心、溫暖、像家。")
    set_page_keywords ('一家三口,寵物安親,寵物美容,寵物住宿,狗狗,貓咪,寵物,狗貓夜間急診,24小時動物醫院')
  end

  def grooming
    set_page_title "寵物美容Grooming"
    set_page_description ("一家三口動物旅館:地址：桃園市桃園區民生路495號之9 33043，電話是03-3363252，email：elite.eah@gmail.com，一家三口動物旅館寵物美容服務，專業的美容師，讓寶貝們更有自信。")
    set_page_keywords ('一家三口,寵物安親,寵物美容,寵物住宿,狗狗,貓咪,寵物,狗貓夜間急診,24小時動物醫院')
  end

  def hotel
    set_page_title "寵物住宿Hotel"
    set_page_description ("一家三口動物旅館:地址：桃園市桃園區民生路495號之9 33043，電話是03-3363252，email：elite.eah@gmail.com，一家三口動物旅館寵物住宿服務，安全、像家、但是擁有更多同伴。")
    set_page_keywords ('一家三口,寵物安親,寵物美容,寵物住宿,狗狗,貓咪,寵物,狗貓夜間急診,24小時動物醫院')
  end

  def about
    set_page_title "關於一家三口about us"
    set_page_description ("一家三口動物旅館:地址：桃園市桃園區民生路495號之9 33043，電話是03-3363252，email：elite.eah@gmail.com，一家三口是一間安全、健康、溫暖的動物旅館，在這裡我們提供寵物美容、寵物住宿、寵物安親的服務。")
    set_page_keywords ('寵物安親,寵物美容,寵物住宿,狗狗,貓咪,寵物,狗貓夜間急診,24小時動物醫院')
  end

  def faqs
    set_page_title "問與答Q&A"
    set_page_description ("一家三口是一間安全、健康、溫暖的動物旅館，在這裡提供寵物美容、寵物住宿、寵物安親的服務，寵物安親住宿須知，寵物美容服務")
    set_page_keywords ('一家三口,寵物安親,寵物美容,寵物住宿,狗狗,貓咪,寵物,狗貓夜間急診,24小時動物醫院')
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/edit.html.erb
<h2>修改最新消息</h2>
<%= simple_form_for [:admin, @post] do |f| %>
<div class = "form-group">
  <%= f.input :title, label: "標題", error: '需要輸入標題' %>
  <%= f.input :content, label: "文章內容", error: "需要輸入文章內容" %>
  </div>
  <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div> 
 <% end %>

app/views/admin/posts/index.html.erb
<div class="space-70"></div>
<h3> 最新文章列表 </h3>

<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增文章", new_admin_post_path, class: "btn btn-primary btn-sm") %> 
</div>

  <table class="table table-bordered">
  <thead>
    <tr>
      <th width="120">#</th>
      <th width="120">文章標題</th>
      <th width="120">文章內容</th>
      <th width="100"> Options</th>
    </tr>
  </thead>
  <tbody>

    <% @posts.each do |post| %>
      <tr>
        <td>
          <%= post.id %>
        </td>
        <td>
          <%= post.title %>
        </td>
        <td>
          <%= markdown(post.content) %>
        </td>
        <td>
          <%= link_to("編輯", edit_admin_post_path(post)) %>
          <%= link_to("刪除", admin_post_path(post), method: :delete, data: {confirm: "Are you sure?"})%>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/admin/posts/new.html.erb
<h2>新增最新消息</h2>
<%= simple_form_for [:admin, @post] do |f| %>
<div class = "form-group">
  <%= f.input :title, label: "標題", error: '需要輸入標題' %>
  <%= f.input :content, label: "文章內容", error: "需要輸入文章內容" %>
  </div>
  <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div> 
 <% end %>