config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]                                          
as :user do
  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
  put 'users' => 'devise/registrations#update', :as => 'user_registration'            
end
  

  root :to => "posts#index"

resources :posts

namespace :admin do
  resources :posts
  end

controller :posts do
  get :daycare
  get :hotel
  get :about
  get :grooming
  get :faqs
end

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :admin_required
  before_action :find_photos
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end


  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to admin_posts_path
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_posts_path
    else
      render :edit
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, alert: '文章已刪除'
  end
  private

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_photos
  def index
    @posts = Post.order("id DESC")
     set_page_title "寵物安親｜寵物住宿｜寵物美容"
     set_page_description (" 一家三口動物旅館成立於2015年10月，位於桃園市桃園區民生路上，一家三口是一間安全、健康、溫暖的動物旅館，在這裡提供寵物美容、寵物住宿、寵物安親的服務。地址：桃園市桃園區民生路495號之9 33043，電話是03-3363252，email：elite.eah@gmail.com")
     set_page_keywords ('一家三口,寵物安親,寵物美容,寵物住宿,寵物,狗狗,貓咪,狗貓夜間急診,24小時動物醫院')
  end

  def show
    @post = Post.find(params[:id])
     set_page_title "最新消息"
     set_page_description ("一家三口動物旅館:地址：桃園市桃園區民生路495號之9 33043，電話是03-3363252，email：elite.eah@gmail.com，一家三口動物旅館最新消息，我們有寵物美容、寵物住宿、寵物安親優質服務。")
     set_page_keywords ('一家三口,寵物安親,寵物美容,寵物住宿,狗狗,貓咪,寵物,狗貓夜間急診,24小時動物醫院')
  end

  def daycare
    set_page_title "寵物安親Daycare"
    set_page_description ("一家三口動物旅館:地址：桃園市桃園區民生路495號之9 33043，電話是03-3363252，email：elite.eah@gmail.com，一家三口動物旅館寵物安親服務，一家三口動物旅館秉持著貼心、溫暖、像家。")
    set_page_keywords ('一家三口,寵物安親,寵物美容,寵物住宿,狗狗,貓咪,寵物,狗貓夜間急診,24小時動物醫院')
  end

  def grooming
    set_page_title "寵物美容Grooming"
    set_page_description ("一家三口動物旅館:地址：桃園市桃園區民生路495號之9 33043，電話是03-3363252，email：elite.eah@gmail.com，一家三口動物旅館寵物美容服務，專業的美容師，讓寶貝們更有自信。")
    set_page_keywords ('一家三口,寵物安親,寵物美容,寵物住宿,狗狗,貓咪,寵物,狗貓夜間急診,24小時動物醫院')
  end

  def hotel
    set_page_title "寵物住宿Hotel"
    set_page_description ("一家三口動物旅館:地址：桃園市桃園區民生路495號之9 33043，電話是03-3363252，email：elite.eah@gmail.com，一家三口動物旅館寵物住宿服務，安全、像家、但是擁有更多同伴。")
    set_page_keywords ('一家三口,寵物安親,寵物美容,寵物住宿,狗狗,貓咪,寵物,狗貓夜間急診,24小時動物醫院')
  end

  def about
    set_page_title "關於一家三口about us"
    set_page_description ("一家三口動物旅館:地址：桃園市桃園區民生路495號之9 33043，電話是03-3363252，email：elite.eah@gmail.com，一家三口是一間安全、健康、溫暖的動物旅館，在這裡我們提供寵物美容、寵物住宿、寵物安親的服務。")
    set_page_keywords ('寵物安親,寵物美容,寵物住宿,狗狗,貓咪,寵物,狗貓夜間急診,24小時動物醫院')
  end

  def faqs
    set_page_title "問與答Q&A"
    set_page_description ("一家三口是一間安全、健康、溫暖的動物旅館，在這裡提供寵物美容、寵物住宿、寵物安親的服務，寵物安親住宿須知，寵物美容服務")
    set_page_keywords ('一家三口,寵物安親,寵物美容,寵物住宿,狗狗,貓咪,寵物,狗貓夜間急診,24小時動物醫院')
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/about.html.erb
 <body>
          <section id="content-region-3" class="padding-40 page-tree-bg-about">
            <div class="container">
                <h1 class="page-tree-text">
                    關於我們About us
                </h1>
            </div>
        </section><!--page tree end here-->
        <div class="space-70"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <div class="flexslider">
                        <ul class="slides">
                            <li><%=image_tag('about-1.jpg', class:"img-responsive",alt:"一家三口動物旅館團體照")%></li>
                            <li><%=image_tag('about-4.jpg', class:"img-responsive",alt:"一家三口動物旅館團體照")%></li>
                            <li><%=image_tag('about-5.jpg', class:"img-responsive",alt:"一家三口動物旅館")%></li>
                        </ul><!--flex slider-->
                </div>
            </div>
                <div class="col-md-5">
                    <h2 class="heading-mini">關於我們</h2>
                    <h5>
                        <p>
                        因家中的巴戈犬摸摸而和黃醫師成為一家人的店長Cherrie，常為著黃醫師分享醫院中大小事的熱忱而感動。而本身愛狗如命的她在醫院成立之際，也一併把動物旅館設計規劃進品湛動物醫院的體系下。 希望能提供給父母們更完整、便利、安心；毛小孩更貼心、安全、健康又舒服的環境。未來將規劃更多的動物課程，將良好的照顧及正確的觀念分享給更多的爸媽們。
                        </p>
                        <p>
                        一家三口動物旅館成立於2015年10月，位於桃園市桃園區民生路上，一家三口是一間安全、健康、溫暖的動物旅館，在這裡提供寵物美容、寵物住宿、寵物安親的服務。
                        </p>
                    </h5>
                    <br>
                    <h2 class="heading-mini">旅館環境</h2>
                    <h5>
                    <p>為提供給各位飼主（爸媽們）安心健康的環境，我們採用了以下的設備。</p>
                    <ul class="icon-list list-unstyled">
                        <li><i class="ion-checkmark-round"></i> 日本Richell睡床、飲水器、圍籠。</li>
                        <li><i class="ion-checkmark-round"></i>採用日本品牌A.P.D.C全系列商品。</li>
                        <li><i class="ion-checkmark-round"></i>獸醫院專用，美國德瑪沛翠絲清耳液。</li>
                        <li><i class="ion-checkmark-round"></i>天然精油洗劑，不添加人工香精、漂白劑。</li>
                        <li><i class="ion-checkmark-round"></i> Paulwhite負離子吹毛機。</li>
                        <li><i class="ion-checkmark-round"></i> 醫療級光觸媒紫外線空氣清淨機。</li>

                    </ul>
                    </h5>
                </div>
            </div>
        </div>         <!--about company row end-->
        <div class="col-md-12">
                    <h4 class="heading-mini">我們的部門</h4>
                </div>

                <div class="col-md-3 col-sm-6 margin-btm-20">
                    <div class="person-section">
                        <%=image_tag('aboutlife-1.jpg', class:"img-responsive",alt:"品湛醫院醫療部")%>
                        <div class="person-desc">
                            <h3>品湛醫院醫療部</span></h3>

                            <p>
                                醫療部位於動物旅館的1樓，來到我們這的寶貝不只享受，更有專業醫療團隊為健康把關。
                            </p>
                        </div>
                    </div><!--person section end-->
                </div><!--person col end-->
                 <div class="col-md-3 col-sm-6 margin-btm-20">
                    <div class="person-section">
                        <%= link_to image_tag('daycare-1.jpg', class:"img-responsive",alt:"寵物住宿部-狗狗區"), hotel_path %>
                        <div class="person-desc">
                            <h3><%= link_to('住宿部-狗狗區',hotel_path) %></h3>

                            <p>
                                溫暖的裝潢，繽紛的顏色，更重要的是我們的初衷，安全、像家但是擁有更多同伴。
                            </p>
                        </div>
                    </div><!--person section end-->
                </div>
                 <div class="col-md-3 col-sm-6 margin-btm-20">
                    <div class="person-section">
                        <%=link_to image_tag('hotellife-12.jpg', class:"img-responsive",alt:"寵物住宿部-貓區"), hotel_path %>
                        <div class="person-desc">
                            <h3><%= link_to('住宿部-貓咪區', hotel_path) %></h3>

                            <p>
                                獨棟的Villa，考量貓咪的習性，讓怕生的貓咪擁有最安心自在的環境。
                            </p>
                        </div>
                    </div><!--person section end-->
                </div>
                 <div class="col-md-3 col-sm-6 margin-btm-20">
                    <div class="person-section">
                        <%=link_to image_tag('grooming-3.jpg', class:"img-responsive",alt:"寵物美容部"), grooming_path %>
                        <div class="person-desc">
                            <h3><%= link_to('美容部', grooming_path) %></h3>

                            <p>
                                專業的美容師團隊，讓寶貝美容後更有自信。
                            </p>
                        </div>
                    </div><!--person section end-->
                </div>
                                <div class="space-70"></div>
        </div>
        <div class="cta-bg">
            <div class="container text-center">
                <h3>安全、像家、但是擁有更多同伴。
                    <a href="tel:(03)3363252", class="btn btn-lg btn-black btn-radius" id = "reservation-about">開始預約</a>
                </h3>
            </div>
        </div>

        <div class="space-70"></div>
        <section id="content-region-2" class="padding-40 parallax-1">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <div class="testimonials">
                            <ul class="slides">
                                <li>
                                    <p class="testi-text">這裡的醫師跟人員都超棒超熱心愛護動物，環境又是無與倫比的乾淨，完全沒有去獸醫院的怪味，醫療儀器又完整先進，很開心桃園有如此高水準的獸醫院跟狗spa跟狗旅館。<p>
                                        <span class="testi-person"> 蓬蓬媽媽 留  </span>
                                </li>
                                <li>
                                    <p class="testi-text">"一家三口美容真是用心又讚！寶貝洗的好乾淨，還跟安親的店長姐姐玩的好高興，真是的讓媽媽安心的好地方！下次財財還是再來！"<p>
                                        <span class="testi-person">財財媽媽 留  </span>
                                </li>
                                <li>
                                    <p class="testi-text">真的很開心找到一家三口，讓我能安心帶他們來美容，在這裡的美容師和保姆姊姊都對旺旺和Teddy很溫柔，以前送去美容都會害怕發抖，現在要接回家都一副不想走了！<p>
                                        <span class="testi-person">旺旺、Teddy媽媽 留  </span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>

<script type="text/javascript">
  var link = document.getElementById("reservation-about");
    analytics.trackLink(link, '表單預約', {
    location: 'Center',
    color: 'blue',
    text: '開始預約',
    CTA: 'form',
    category: 'about page',
    type: 'Button',
    pageTitle: document.title
  });
</script>

app/views/posts/daycare.html.erb
<body>
          <section id="content-region-3" class="padding-40 page-tree-bg-daycare">
            <div class="container">
                <h1 class="page-tree-text">
                    安親DayCare
                </h1>
            </div>
        </section><!--page tree end here-->
        <div class="space-70"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <div class="flexslider">
                        <ul class="slides">
                            <li><%=image_tag('daycarelife-1.jpg', class:"img-responsive",alt:"一家三口動物旅館寵物安親狗狗玩樂")%>
                            <li><%=image_tag('daycarelife-2.jpg', class:"img-responsive",alt:"一家三口動物旅館寵物安親狗狗玩樂")%></li>
                            <li><%=image_tag('daycarelife-3.jpg', class:"img-responsive",alt:"一家三口動物旅館寵物安親狗狗Richell睡床")%></li>
                            <li><%=image_tag('daycarelife-4.jpg', class:"img-responsive",alt:"一家三口動物旅館寵物安親狗狗玩樂")%></li>
                            <li><%=image_tag('daycarelife-5.jpg', class:"img-responsive",alt:"一家三口動物旅館寵物安親狗狗玩樂")%></li>
                        </ul><!--flex slider-->
                </div>
            </div>
                <div class="col-md-5">
                     <p>
                        一家三口動物旅館提供安全溫馨的安親時間，讓寶貝玩到開心翻肚肚又能擁有安心的午覺時光，爸爸媽媽及時需要，我們一直都在。
                    </p>
                    <br>
                    <ul class="icon-list list-unstyled">
                        <li><i class="ion-checkmark-round"></i> 日本Richell睡床、飲水器、圍籠。</li>
                        <li><i class="ion-checkmark-round"></i> 寵物褓姆全天陪伴。</li>
                        <li><i class="ion-checkmark-round"></i> 不關籠，提供寵物自由社交(大、中、小型犬分區活動)。</li>
                        <li><i class="ion-checkmark-round"></i> 醫療級光觸媒紫外線空氣清淨機。</li>
                    </ul>
                    <h5>第一次來嗎？請詳閱<%= link_to('安親前須知',faqs_path(anchor: "hotelknow")) %> </h5>
                    <h2 class="heading-mini">安親價目表</h2>
                    <h5><div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                          <tr>
                            <th>狗狗體型</th>
                            <th>安親Day Care/(時)</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>體重 小於6KG</td>
                            <td>NT 50起</td>
                          </tr>
                          <tr>
                            <td>體重 &nbsp6-10KG</td>
                            <td>NT 60起</td>
                          </tr>
                          <tr>
                            <td>體重  &nbsp10-15KG</td>
                            <td>NT 70起</td>
                          </tr>
                          <tr>
                            <td>體重  &nbsp15-20KG</td>
                            <td>NT 80起</td>
                          </tr>
                        </tbody>
                      </table>
                      </div>


                </div></h5>
            </div>
        </div>
            <div class="space-70"></div>
            <div class="col-md-12">
                    <h4 class="heading-mini">安親服務及環境</h4>
                </div>

                <div class="col-md-3 col-sm-6 margin-btm-20">
                    <div class="person-section">
                        <%=image_tag('daycare-1.jpg', class:"img-responsive",alt:"寵物安親狗狗遊戲區")%>
                        <div class="person-desc">
                            <h3>狗狗遊戲區</h3>

                            <p>
                                中小型狗狗們活動的場所，有各式各樣玩具，還有同伴們，陪伴一同擁有開心的時光。
                            </p>
                        </div>
                    </div><!--person section end-->
                </div><!--person col end-->
                 <div class="col-md-3 col-sm-6 margin-btm-20">
                    <div class="person-section">
                        <%=image_tag('daycare-2.jpg', class:"img-responsive",alt:"寵物安親DAYCARE澳洲Molly mutt 100%純棉時尚床")%>
                        <div class="person-desc">
                            <h3>澳洲Molly mutt 100%純棉時尚床</h3>

                            <p>
                                molly mutt睡床採用100%純棉布料，提供給狗狗們舒適又透氣的休息空間。
                            </p>
                        </div>
                    </div><!--person section end-->
                </div>
                 <div class="col-md-3 col-sm-6 margin-btm-20">
                    <div class="person-section">
                        <%=image_tag('daycarelife-7.jpg', class:"img-responsive",alt:"寵物安親DAYCARE陪伴玩具")%>
                        <div class="person-desc">
                            <h3>陪伴玩具 </h3>

                            <p>
                                讓寶貝不無聊，我們精心準備許多玩具，能在這空間裡充分互動。
                            </p>
                        </div>
                    </div><!--person section end-->
                </div>
                 <div class="col-md-3 col-sm-6 margin-btm-20">
                    <div class="person-section">
                        <%=image_tag('daycare-4.jpg', class:"img-responsive",alt:"醫療級光觸媒紫外線空氣清淨機")%>
                        <div class="person-desc">
                            <h3>醫療級光觸媒紫外線空氣清淨機</h3>

                            <p>
                                讓寶貝能在乾淨空氣中開心玩樂，不用擔心外面的髒空氣。
                            </p>
                        </div>
                    </div><!--person section end-->
                </div>
     <!--about company row end-->
       <div class="space-50"></div>
        <section id="content-region-2" class="padding-40 parallax-1">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <div class="testimonials">
                            <ul class="slides">
                                <li>
                                    <p class="testi-text">謝謝momo 姐姐陪蓬蓬玩整個下午，他開心的咧，下次姐姐也要在喔！也謝謝所有人員的細心照顧，謝謝喔<p>
                                        <span class="testi-person">蓬蓬媽媽 留  </span>
                                </li>
                                <li>
                                    <p class="testi-text">"一家三口美容真是用心又讚！寶貝洗的好乾淨，還跟安親的店長姐姐玩的好高興，真是的讓媽媽安心的好地方！下次財財還是再來！"<p>
                                        <span class="testi-person">財財媽媽 留  </span>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </section> <!--testimonials section end here-->
     <div class="space-50"></div>
        </div>
        <div class="cta-bg">
            <div class="container text-center">
                <h3>不想讓你的寶貝自己在家嗎？
                    <a href="tel:(03)3363252", class="btn btn-lg btn-black btn-radius" id = "reservation-daycare">馬上預約</a>
                </h3>
            </div>
        </div>
    </body>
<script type="text/javascript">
  var link = document.getElementById("reservation-daycare");
    analytics.trackLink(link, '表單預約', {
    location: 'Center',
    color: 'blue',
    text: '開始預約',
    CTA: 'form',
    category: 'daycare page',
    type: 'Button',
    pageTitle: document.title
  });
</script>

app/views/posts/index.html.erb
    <body>
        <section id="slider-sec" class="slider-reg">
            <div class="main-flex-slider">
                <ul class="slides">
                    <li>
                        <figure>
                            <%=image_tag('slider-1.jpg', class:"img-responsive",alt:"寵物安親DAYCARE")%>
                            <figcaption class="slider-overlay ">
                                <div class="slider-text animated fadeInDown">
                                    <h1><%= link_to('安親DAYCARE',daycare_path) %></h1>
                                    <p>不想讓你的寶貝自己在家嗎？</p>
                                    <p class="slide-btn">
                                    <%= link_to('瞭解更多',daycare_path, class: 'btn btn-white btn-lg', id: 'knowmore')%>
                                    </p>
                                </div>
                            </figcaption>
                        </figure>
                    </li>
                    <li>
                        <figure>
                            <%=image_tag('slider-3.jpg', class:"img-responsive",alt:"寵物住宿HOTEL")%>
                            <figcaption class="slider-overlay">
                                <div class="slider-text">
                                    <h1><%= link_to('住宿HOTEL',hotel_path) %></h1>
                                   <p>安全、像家、但是擁有更多同伴。</p>
                                    <p class="slide-btn"><%= link_to("瞭解更多", hotel_path,
                                        class: "btn btn-white btn-lg", id: 'knowmore')%></p>
                                </div>
                            </figcaption>
                        </figure>
                    </li>
                    <li>
                        <figure>
                            <%=image_tag('slider-2.jpg', class:"img-responsive",alt:"寵物美容GROOMING")%>
                            <figcaption class="slider-overlay">
                                <div class="slider-text">
                                    <h1><%= link_to('美容GROOMING',grooming_path) %></h1>
                                    <p>專業的美容師，讓寶貝們更有自信。</p>
                                    <p class="slide-btn"><%= link_to("瞭解更多", grooming_path,
                                        class: "btn btn-white btn-lg", id: 'knowmore')%></p>

                                </div>
                            </figcaption>
                        </figure>
                    </li>
                </ul>
            </div>
        </section><!--main flex slider end-->
        <div class="space-70"></div>

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="heading-sec">服務項目</h2>
                </div>
            </div><!--row-->
            <div class="row">
                <div class="col-md-4 col-sm-6 margin-btm-40">
                    <div class="portfolio-sec">
                        <div class="portfolio-thumnail">
                                <%= link_to image_tag('service-1.jpg', class:"img-responsive",alt:"寵物安親Daycare"),daycare_path %>
                            </a>
                        </div>
                        <div class="portfolio-desc text-center">
                            <h4 class="portfolio-post-title">安親DAYCARE</h4>
                            <h5><span class="portfolio-post-cat">讓你的毛小孩們有個愉快的時間</span></h5>
                            <h4><%= link_to("瞭解更多", daycare_path,class: "btn theme-btn-default btn-lg")%></h4>
                        </div>
                    </div>
                </div><!--portfolio item -->
                <div class="col-md-4 col-sm-6 margin-btm-40">
                    <div class="portfolio-sec">
                        <div class="portfolio-thumnail">
                                <%= link_to image_tag('service-2.jpg', class:"img-responsive",alt:"寵物住宿pethotel"), hotel_path %>
                            </a>
                        </div>
                        <div class="portfolio-desc text-center">
                            <h4 class="portfolio-post-title">住宿HOTEL</h4>
                            <span class="portfolio-post-cat">提供給你最舒適及最安心的環境</span>
                            <h4><%= link_to("瞭解更多", hotel_path,class: "btn theme-btn-default btn-lg")%></h4>
                        </div>
                    </div>
                </div><!--portfolio item -->
                <div class="col-md-4 col-sm-6 margin-btm-40">
                    <div class="portfolio-sec">
                        <div class="portfolio-thumnail">
                            <a href="portfolio-single.html">
                                <%= link_to image_tag('service-3.jpg', class:"img-responsive",alt:"寵物美容grooming"), grooming_path %>
                            </a>
                        </div>
                        <div class="portfolio-desc text-center">
                            <h4 class="portfolio-post-title">美容SPA</h4>
                            <span class="portfolio-post-cat">使用APDC沐浴乳及全程手工吹整毛髮，讓寶貝們洗個舒適。</span>
                            <h4><%= link_to("瞭解更多", grooming_path,class: "btn theme-btn-default btn-lg")%></h4>
                        </div>
                    </div>
                </div><!--portfolio item -->
           </div><!--row portfolio item-->
        </div><!--recent work container end-->
        <div class="space-70"></div>
       <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="heading-sec">最新消息</h3>
                </div>
            </div><!--row-->
            <div class="row">
                <% @posts.first(3).each do |post| %>
                <div class="col-md-4 col-sm-6 margin-btm-20">
                    <div class="news-sec">
                        <div class="news-thumnail">
                            <h4 class="blog-post-title">
                                <%=link_to(post.title, post_path(post))%>
                            </h4>
                            <span class="news-post-cat"><%= post.created_at.strftime("%B %d, %Y") %></span>
                            <p><%= markdown(post.content) %></p>
                        </div>
                    </div>
                </div><!--latest news items-->
                <% end %>
            </div><!--row end-->
        </div><!--container recent news end-->

                <div class="space-70"></div>
        <section id="content-region-2" class="padding-40 parallax-1">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <div class="testimonials">
                            <ul class="slides">
                                <li>
                                    <p class="testi-text">這裡的醫師跟人員都超棒超熱心愛護動物，環境又是無與倫比的乾淨，完全沒有去獸醫院的怪味，醫療儀器又完整先進，很開心桃園有如此高水準的獸醫院跟狗spa跟狗旅館。<p>
                                        <span class="testi-person">蓬蓬媽媽 留  </span>
                                </li>
                                <li>
                                    <p class="testi-text">一家三口美容真是用心又讚！寶貝洗的好乾淨，還跟安親的店長姐姐玩的好高興，真是的讓媽媽安心的好地方！下次財財還是再來！<p>
                                        <span class="testi-person">財財媽媽 留  </span>
                                </li>
                                <li>
                                    <p class="testi-text">妮妮在這邊洗澡眼睛回去都不會紅紅的喔! 感覺洗劑真的很天然比較不會刺激眼睛，而且毛髮也越洗越柔亮了!<p>
                                        <span class="testi-person"> 妮妮哥哥 留  </span>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </section> <!--testimonials section end here-->
        <div class="space-50"></div>
        <div class="cta-bg">
            <div class="container text-center">
                <h3>貼心、溫暖、像家。
                    <a href="tel:(03)3363252" class="btn btn-lg btn-black btn-radius" id = "reservation1">立即預約</a>
                </h3>
            </div>
        </div>
    </body>
<script type="text/javascript">
  var link = document.getElementById('reservation1');
    analytics.trackLink(link, '表單預約', {
    location: 'Center',
    color: 'blue',
    text: '開始預約',
    CTA: 'form',
    category: 'Home Page',
    type: 'Button',
    pageTitle: document.title
  });
  var link2 = document.getElementById('knowmore');
    analytics.trackLink(link2, '瞭解更多', {
    location: 'Center',
    color: 'blue',
    text: '瞭解更多',
    CTA: 'phone',
    category: 'Home Page',
    type: 'Button',
    pageTitle: document.title
  });
</script>

app/views/posts/show.html.erb
        <section id="content-region-3" class="padding-40 page-tree-bg">
            <div class="container">
                <h3 class="page-tree-text">
                    最新消息
                </h3>
            </div>
        </section><!--page-tree end here-->
        <div class="space-70"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="heading-sec">
                        <%= @post.title %>
                    </h2>
                    <p><%= markdown(@post.content) %></p>
                </div>
            </div>
        </div><!--full width page end-->