config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]                                          
as :user do
  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
  put 'users' => 'devise/registrations#update', :as => 'user_registration'            
end
  

  root :to => "posts#index"

resources :posts

namespace :admin do
  resources :posts
  end

controller :posts do
  get :daycare
  get :hotel
  get :about
  get :grooming
  get :faqs
end

  

end

app/views/common/_footer.html.erb
        <footer id="footer-option">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 margin-btm-20">
                        <div class="footer-col margin-btm-20">
                            <h3> recent Instagram</h3>
                            <div class = "flexslider">
                                <ul class = "slides">
                            <% @photos.each do |photo| %>
                            <li><%= image_tag(photo.images.standard_resolution.url, :class => "img-responsive") %>
                                <p class = "flex-caption">
                                   <% if photo.caption %>
                                   <%= photo.caption.text %>
                                   <% else %>
                                    <%=  %></p>
                                    <% end %>
                            <% end %>
                                </ul>
                            </div>
                            </div>
                    </div><!--footer col end-->
                    <div class="col-md-4 margin-btm-20">
                        <div class="footer-col">
                         <h3>Facebook</h3>
                                <div class="fb-page" data-href="https://www.facebook.com/Elite.AH" data-height="250" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/Elite.AH"><a href="https://www.facebook.com/Elite.AH">品湛動物醫院 Elite Animal Hospital / 一家三口動物旅館 Going Home Animal Casa</a></blockquote></div></div>
                        </div>
                        
                    </div><!--footer col end-->
                    <div class="col-md-4 margin-btm-20">
                     <div class="footer-col margin-btm-20">
                        <div itemscope itemtype="http://schema.org/LocalBusiness">
                            <h3>contact info</h3>
                        <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
                            <p><i class="ion-home"></i>
                            <span itemprop="addressLocality">桃園市</span>
                            <span itemprop="streetAddress">桃園區民生路495號之9 </span>
                            </p>
                        </div> 
                            <p><i class="ion-ios-location-outline"><a href="https://goo.gl/maps/aG9WhkB8BAn" target="_blank">&nbsp取得前往路線</i></a></p>
                            <p><i class="ion-iphone"><span itemprop="telephone"><a href="tel:(03)3363252">&nbsp&nbsp預約專線：03-3363252</i></span></a></p>

                            <p><i class="ion-email"><a href="mailto:elite.eah@gmail.com" itemprop="email"></i>&nbspE-mail：elite.eah@gmail.com</a></p>
                            <p><i class="ion-ios-time-outline"></i><meta itemprop="openingHours" content="Mo-Su 10:00-22:00">&nbsp營業時間：每日10:00 ~ 22:00 </p>
                            <p><i class="ion-ios-paw-outline"></i>桃市特寵業字第411號</png>
                        </div>
                    </div>    
                     </div><!--footer col end-->
                </div>
            </div>
            <div class="footer-copyright">
                <div class="container">
                    <div class="row">
                        <div class="col-md-1 footer-logo">
                            <%=link_to image_tag("home_white.png", alt: "一家三口動物旅館",:class => 'img-responsive'), root_path%>
                        </div>
                        <div class="col-md-5">
                            <p>&copy; copyright 2016.一家三口動物旅館 all right reserved</p>
                        </div>
                        <div class="col-md-6 ">
                            <ul class="list-inline footer-nav">
                                <li><%= link_to("Home", root_path)%></li>
                                <li><%= link_to("安親", daycare_path,) %></li>
                                <li><%= link_to("住宿", hotel_path,) %></li>
                                <li><%= link_to("美容", grooming_path,) %></li>
                                <li><%= link_to("問與答", faqs_path,) %></li>
                                <li><a  href="tel:(03)3363252", target = "_blank">預約</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer><!--#footer option end-->

app/views/common/_navbar.html.erb
<header class="header-main">
            <div class="navbar navbar-default" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button><a id="top"></a>
                        <%=link_to image_tag("logo.png", :class => 'img-responsive',:alt =>
                        '一家三口動物旅館'), root_path, :class => 'navbar-brand' %>
                    </div>
                    <div class="navbar-collapse collapse">

                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <%= link_to("Home", root_path)%>
                            </li>
                            <li>
                                <%= link_to("安親", daycare_path) %>
                                </li>
                            <li class="dropdown">
                                <%= link_to("住宿", hotel_path) %>
                            </li>
                            <li class= "dropdown">
                                <%= link_to("美容", grooming_path) %>
                            </li>
                            <li>
                                <%= link_to("關於我們", about_path) %>
                            </li>
                            <li class="social-nav"><a href="https://www.facebook.com/Elite.AH" target="_blank"><i class="ion-social-facebook"></i></a></li>
                            <li class="social-nav"><a href="https://instagram.com/elite.eah/" target="_blank"><i class="ion-social-instagram" target="_blank"></i></a></li>
                        </ul>

                    </div><!--/.nav-collapse -->
                </div><!--/.container-->
            </div><!--navigation end-->

        </header><!--header main end-->

app/views/common/_optimizely.html.erb
<script src="//cdn.optimizely.com/js/4563460708.js"></script>

app/views/common/_segment_io.erb
<script type="text/javascript">
!function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.1.0";
analytics.load("xU4zVgz7WWJjn1GbWfr2lwjoIQYZMSPb");
analytics.page()
}}();
</script>

app/views/common/_segment_io.html.erb
<script type="text/javascript">
!function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.1.0";
analytics.load("xU4zVgz7WWJjn1GbWfr2lwjoIQYZMSPb");
analytics.page()
}}();
</script>

app/views/common/_sumome.html.erb
<script src="//load.sumome.com/" data-sumo-site-id="078f4c9706925ae5fd6f432183240bcf9d2dedc5c5a4009006af5d161910b271" async="async"></script>

app/views/common/_zopin.html.erb
<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="//v2.zopim.com/?3by2wQLoM1O3yhdm492VCUvelZ014sVG";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>
<!--End of Zopim Live Chat Script-->

app/views/common/sumome.html.erb
<script src="//load.sumome.com/" data-sumo-site-id="078f4c9706925ae5fd6f432183240bcf9d2dedc5c5a4009006af5d161910b271" async="async"></script>